spring:
  sql:
    init:
      mode: never
  config:
    import: 'consul:'
  application:
    name: salas-service

  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        instance-id: salas-service-i1